### PR TITLE
configured Devise for user sign up

### PR DESCRIPTION
**Pull request by brendanmcgivern**

### CODE REVIEW

**Comment by droberts84** [comment]
Rspec has an error.  That is a dead giveaway its not quite ready to merge :)  This should be an easy fix.

In the future, feel free to break up your commits into smaller logical pieces.  Feel free to have WIP commits or commit anytime you get a small piece of code working.

Otherwise it looks good.

**Comment by brendanmcgivern** [comment]
Which file has the error?  When I run my `user_spec.rb` and my feature spec I don't get any failures.  Do I have a logic error?Date: Wed, 17 Jun 2015 11:09:29 -0700

**Comment by droberts84** [comment]
Try running your entire test suite by typing "rspec"

**Comment by brendanmcgivern** [comment]
The error was caused because I deleted the `todos_helper.rb` file yesterday, so I deleted the `todos_helper_spec.rb` file and that eliminated the error.  Date: Wed, 17 Jun 2015 15:39:20 -0700

**Comment by droberts84** [comment]
:+1:

**Comment by brendanmcgivern** [comment]
Quick question.  Do I merge both pull requests or do I only merge my most recent pull request since my user-sign-in branch was a branch off of user-sign-up?Date: Wed, 17 Jun 2015 18:10:52 -0700

**Comment by droberts84** [comment]
Merging either would work.. but if you merge the most recent first.. that will also merge in a lot of the the code from the older PR.  I would recommend merging the older first.

**Pull request merged**
